### PR TITLE
First attempt at incorporating sphinx-apidoc into build process

### PR DESCRIPTION
**Pull request by ns-rse**
Thanks for writing and sharing this action, really useful.

I found it didn't appear to include the results of `sphinx-apidoc` to convert Python module docstrings to restructured text prior to building the HTML so have had a go at doing so. It appears to work for me (but that doesn't mean it will work for everyone!).

I introduced two new variables to allow users to configure `sphinxapidopts` (options to pass to `sphinx-apidoc`) and `sphinxapiexclude` (patterns to pass to `sphinx-apidoc` that should be excluded).

Please do let me know if there is anything I've got wrong or can improve, still wet behind the ears with GitHub Actions but keen to learn.

### CODE REVIEW

**Review by dprada — APPROVED** [review]
Thanks @ns-rse!

Let's release your changes as version 1.1.0. Projects using 1.0.0 can always do it.

Thanks again for your contribution. For any future bug or enhancement, please make yourself at home to participate.

**Comment by dprada** [comment]
The README.md file needs to be updated. Give me some time to do it. 👍🏻

**Comment by dprada** [comment]
Version v1.1.0-beta released (with your contribution). With the two GitHub Actions that we have, we always give some weeks to a beta version before releasing the "stable" action.

**Comment by ns-rse** [comment]
Excellent, thanks @dprada glad my small contribution is useful :+1: 

I'll look at updating the `README.md` which I should have done in the first place.

**Pull request merged**
